[package]
name = "mathstool"
version = "0.1.0"
authors = ["mitchpk <mitchellpkempen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rug = "1.12"
thiserror = "1.0"
